### ISSUE TITLE
Change you insta password

### ISSUE THREAD

**Issue by oliverguhr** [edouardthom/InstaBot#1]
If this is your Insta password, you should change it ;) 

https://github.com/edouardthom/InstaBot/blob/6096a4a6360cd522ba6415a44d3c5e18f5ecdabc/instabot_main.py#L15

**Comment by edouardthom** [comment]
omg thanks a bunch ! I'm usually neglecting security matters...
Btw if I may ask, how did you stumble upon my new repo ?

Thanks again and have a great day :)

Le lun. 16 nov. 2020 à 10:25, Oliver Guhr <notifications@github.com> a
écrit :

**Comment by oliverguhr** [comment]
Apparently I follow you - I am not sure why :) Today your repo was on my GitHub feed. I clicked on it because I thought about creating an Insta bot some time ago. So I was just curious and looked at the strategy that you implemented.

**Comment by oliverguhr** [comment]
PS: Do I need something besides selenium to run your code?

**Comment by edouardthom** [comment]
Disclaimer : it is a work in progress

The pure python part that can run in local just requires python 3.7 +
selenium + chrome + the adapted chromedriver that your OS needs to be able
to find (in macos i put it in sth like /usr/bin/local) + a couple other
usual data libraries such as pandas and numpy

Then the goal is to make it run perpetually on a free AWS instance, and the
instance will in the future send emails with daily stats.
That last part in not fully done, still a bit buggy, also I'll sum up
everything with some tuto once the MVP is functional ---> stay tuned :p

**Comment by oliverguhr** [comment]
Sounds great! I'll come back later :)
